config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "dashboard#index"
  get "/customize_complete" => "dashboard#customize_complete", as: "customize_interface"
  post "/customize_complete" => "dashboard#customize_complete", as: "customize_interface_form"
  get "/error404" => "dashboard#error404"
  get "/error500" => "dashboard#error500"
  get "/error403" => "dashboard#error403"
  get 'opportunities' => 'opportunities#index'
  get "/profile_volunteer" => "dashboard#profile_volunteer"
  #get "/profile_organization" => "organization#profile_organization"

  resources :organization
  get "/hours" => "dashboard#hours", as: "hours"
  get "/notifs" => "dashboard#notifs", as: "notifs"
  get "/history" => "dashboard#history", as: "history"
  get "/notifications" => "organization#notifications", as: "notifications"
  get "/stats/:id" => 'organization#stats', as: "stats"
  get "/volunteers/:id" => 'organization#volunteers', as: "volunteers"
  get "/reviews/:id" => 'organization#reviews', as: "reviews"
  get "/histories/:id" => 'organization#histories', as: "histories"
  get "/opps/:id" => 'organization#opps', as: "opps"
  get "/opportunities/:id/clone" => 'opportunities#clone', as: "clone_opportunity"
  post 'organization/approve'
  post 'organization/deny'

  resources :challenges
  get "/stat" => "admin#statistics"
  get "/requests" => "admin#requests"
  get "/organizations" => "admin#organizations"
  get "/goals" => "admin#goals"

  resources :opportunities
  get "/secret" => "organization#secret"
  get '/auth/duke-oauth2/callback', to: 'dashboard#create'
  get "/feed_volunteer" => "dashboard#feed_volunteer"
  post "/feed_volunteer" => "dashboard#feed_volunteer", as: "temp_form"
  post "/feed_organization" => "organization#feed_organization", as: "org_form"
  get "/feed_organization" => "organization#feed_organization"
  get "/admin" => "admin#admin_home"
  #get "/posting_volunteer" => "dashboard#posting_volunteer"
  get "/opportunities/:id/contact_volunteers" => "opportunities#contact_volunteers", as: "contact_volunteers"
  post "/opportunities/:id/contact" => "opportunities#contact", as: "contact_path"
  get "/opportunities/:id/view_volunteers" => "opportunities#view_volunteers", as: "view_volunteers"
  get "/organization/:id/like" => "organization#like", as: "like_action"
  get "/opportunities/:id/like" => "opportunities#like", as: "like_action_opportunity"

  get "/admin_home" => "admin#admin_home"
  get "/admin_settings" => "admin#admin_settings", as: "admin_settings"
  patch "/admin_home" => "admin#update_settings", as: "update_settings"
  post "/admin_home" => "admin#update_admin", as: "admin_form"
  
  get "/onboard" => "onboarding#onboard"
  get "/volunteer_partial" => "onboarding#volunteer_partial"
  get "/organization_partial" => "onboarding#organization_partial"
  get "/complete" => "onboarding#complete", as: "onboarding_complete"
  post "/complete" => "onboarding#complete", as: "onboarding_complete_form"
  post 'admin/approve'
  post 'admin/deny'

  get "/edit_user/:id" => "dashboard#edit_user", as: "edit_user"
  patch "/profile_volunteer" => "dashboard#update_user", as: "update_user"
  resources :dashboard, only: [:show]

  get "/edit_custom/:id" => "organization#edit_custom", as: "edit_custom"

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/controllers/dashboard_controller.rb
require "mini_magick"

class DashboardController < ApplicationController

  # any line with 'if Interface.first.nil? redirect to root_url and return' ensures that the user is taken to the
  # homescreen and asked to create/customize an interface if it doesn't already exist (usually occurs with initial build)

# sets current user and interface
  def index
    @current_user = current_user
    if !Interface.first.nil?
      @interface = Interface.first
    end
  end

  def error404
    if Interface.first.nil?
      redirect_to root_url and return
    end
  end

  def error500
    if Interface.first.nil?
      redirect_to root_url and return
    end
  end

  def error403
    if Interface.first.nil?
      redirect_to root_url and return
    end
  end

  def customize_complete
    
    #sets custom interface settings: name, tagline, institution, color scheme
    interface = Interface.start_custom(params[:interface_name], params[:interface_tagline],
      params[:institution], params[:primary_color], params[:secondary_color], params[:accent_color], params[:user][:time_zone])

    #sets interface vectors and logos
    Interface.add_images(interface, params[:interface_vector], params[:interface_logo], params[:school_logo])

    #creates and sets landmarks with addresses for filter options
    Landmark.generate_landmarks(interface, params[:landmark_name1], params[:landmark_address1],
      params[:landmark_name2], params[:landmark_address2], params[:landmark_name3], params[:landmark_address3])

    #sets authentication credentials
    if params[:facebookauth]
      if !params[:facebook_client_id].blank? && !params[:facebook_client_secret].blank? && !params[:facebook_redirect].blank?
        fb = OAuthStrategy.create(name: "facebook", client_id: params[:facebook_client_id], client_secret: params[:facebook_client_secret], redirect_url: "#{params[:facebook_redirect]}/users/auth/facebook/callback")
        interface.o_auth_strategies << fb
      end
    end
    if params[:googleauth]
      if !params[:google_client_id].blank? && !params[:google_client_secret].blank? && !params[:google_redirect].blank?
        goog = OAuthStrategy.create(name: "google", client_id: params[:google_client_id], client_secret: params[:google_client_secret], redirect_url: "#{params[:google_redirect]}/users/auth/google_oauth2/callback")
        interface.o_auth_strategies << goog
      end
    end

    #creates new admin
    new_admin = OrgAdmin.initialize_admins(params[:institution], params[:admin_name], params[:admin_email])

    #shows temporary password
    if new_admin.save
      flash[:success] = "We have created an admin account for #{new_admin.name}! You have temporarily been given the password '#{new_admin.password}', so change it immediately from the login page."
    end

    interface.save
    #overwrites new colors
    File.atomic_write('/webapp/app/assets/stylesheets/set_color.scss') do |file|
      template = File.open('/webapp/app/assets/stylesheets/globalvars.txt')
      file.write(template.read + '$main-color: ' + Interface.first.primary_color + "; $secondary-color: " + Interface.first.secondary_color + "; $accent-color: " + Interface.first.accent_color + ";")
      template.close
    end
    #rails asset:compile
  end

  def create
    if Interface.first.nil?
      redirect_to root_url and return
    end

    @user = User.find_or_create_from_auth_hash(auth_hash)
    selfcurrent_user = @user
    redirect_to '/'
  end

  # Render hours
  def hours
    if Interface.first.nil?
      redirect_to root_url and return
    end

    @opportunities = Opportunity.joins(:users).where(users: { id:current_user.id})
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # Render notifications
  def notifs
    if Interface.first.nil?
      redirect_to root_url and return
    end

    @notifications = Notification.where(recipient:current_user).reverse
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # Render volunteer history
  def history
    if Interface.first.nil?
      redirect_to root_url and return
    end

    @user =current_user
    @opportunities = Opportunity.where(id: ArchivedOpportunity.joins(:users).where(
      users: { id:current_user.id}).pluck(:opportunity_id))
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # Filters opportunities within the distance from slider from user location
  def feed_volunteer
    if Interface.first.nil?
      redirect_to root_url and return
    end

    @interface = Interface.first
    #var to determine navbar link colors
    @ifFeed = true

    check_auth

    #checks location to filter by
    if !params[:location].nil?
      $location = Landmark.first if params[:location] == "loc1"
      $location = Landmark.second if params[:location] == "loc2"
      $location = Landmark.third if params[:location] == "loc3"
    else
      $location = Landmark.first
    end

    #sets selected tags in mobile or standard view
    if params[:tags].nil?
      @tags = params[:mobile_tags]
    else
      @tags = params[:tags]
    end

    #gets selected distance radius from slider
    if params[:distance].nil?
      @slider = 15
    else
      @slider = params[:distance]
    end

    # Puts featured posts at the top ONLY if no filter has been applied
    if params[:page].nil?
      $opportunities = Opportunity.sorting_opps(!params[:upcoming].to_i.zero?,
        !params[:highrated].to_i.zero?, params[:freq], params[:remo], params[:distance],
        params[:location], @tags, false, nil).distinct
    end

    $opportunities = $opportunities.paginate(:page => params[:page], :per_page => 5)

    @organizations = Organization.all
    @opportunities = $opportunities

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit_user
    if Interface.first.nil?
      redirect_to root_url and return
    end

    @address = current_user.address
    @tags = Tag.all
  end

  def update_user
    if Interface.first.nil?
      redirect_to root_url and return
    end

    if(update_params)
      redirect_to profile_volunteer_path
    else
      render 'edit_user'
    end
  end

  private def update_params
    if Interface.first.nil?
      redirect_to root_url and return
    end

    current_user.update(major: nil, school: nil, degree: nil, grad_year: nil, department: nil)

    # Updating user name, gender, phone, email, affiliation, and description
    current_user.update(name: params[:user][:name], gender: params[:gender], phone: params[:user][:phone],
      affiliation: params[:affiliation], description: params[:description].html_safe)

    # Updating address
    if current_user.address.nil?
      if !params[:address].nil?
        user_address = {}
        params[:address].each {|k,v| user_address[k]=v}
        current_user.build_address(user_address)
        current_user.save
      end
    else
      current_user.address.update(street: params[:user][:street], city: params[:user][:city],
        state: params[:user][:state], zip: params[:user][:zip])
    end

    # Updating major
    case current_user.affiliation
    when "Undergraduate student"
      if params[:user][:major].nil?
        current_user.update(major: params[:major], grad_year: params[:grad_year])
      else
        current_user.update(major: params[:user][:major], grad_year: params[:user][:grad_year])
      end
    when "Graduate/professional student"
      if params[:user][:school].nil?
        current_user.update(school: params[:school], grad_year: params[:grad_year])
      else
        current_user.update(school: params[:user][:school], grad_year: params[:user][:grad_year])
      end
    when "Alumni"
      if params[:user][:degree].nil?
        current_user.update(degree: params[:degree], grad_year: params[:grad_year])
      else
        current_user.update(degree: params[:user][:degree], grad_year: params[:user][:grad_year])
      end
    else
      if params[:user][:department].nil?
        current_user.update(department: params[:department])
      else
        current_user.update(department: params[:user][:department])
      end
    end

    # Updating tags
    current_user.tags.each do |n|
      current_user.tags.delete(n)
    end
    tags = params[:tags]
    if !tags.nil?
        tags.each do |tag|
            current_user.tags << Tag.where(name: tag)
        end
    end

    # Adding profile pic
    if params[:user][:profile_pic].nil?
      if !current_user.pictures.find_by_name("User#{current_user.id}pfp").nil?
        current_pfp =current_user.pictures.find_by_name("User#{current_user.id}pfp")
      current_user.pictures.delete(current_pfp)
        Picture.delete(current_pfp)
      end
      pfp = Picture.new(name: "User#{current_user.id}pfp", imageable_id:current_user.id,
        imageable_type: "#{current_user.class}")
      pfp.image = params[:user][:profile_pic]
      pfp.save!
      current_user.pictures << pfp
    end
  end

  def profile_volunteer
    if Interface.first.nil?
      redirect_to root_url and return
    end

    #Variable for determining navbar link colors
    @interface = Interface.first
    @ifDashboard = true
    check_auth
    current_user.opportunities.each do |opportunity|
      if (!opportunity.active || opportunity.ongoing) && params.has_key?(opportunity.id.to_s)
        #User can provide feedback
        if !params[:description].blank?
          feedback = Feedback.new(description:params[:description], anonymous:!params[:anonymous].nil?)
          feedback.organization = opportunity.organization
          feedback.user =current_user
          feedback.opportunity = opportunity
          feedback.save
          opportunity.organization.users.each do |user|
            Notification.create(recipient: user, actor:current_user, action:
              "has_submitted_feedback_for_your_organization", notifiable: feedback)
          end
        end
        #Archive opportunity

app/views/dashboard/feed_volunteer.html.erb
<!-- problems to fix:
can we customize the checkboxes and slider?
filter button too
smh the size of the bookmark
fixed column sizes?
can we unclick the radio buttons
display of date/time and location
tags D:
-->

<!DOCTYPE html>
<html class="grey-background">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello Bulma!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    </head>

    <body>

  <!-- navigation bar -->
    <%= render "layouts/navbar"%>

    <!-- left bar, contains filtering options -->
    <div class="columns">
      <div class="dropdown is-hidden-tablet is-fullwidth">
        <div class="dropdown-trigger">
          <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
            <span>Sort & Filter</span>
            <span class="icon is-small">
              <i class="fas fa-angle-down" aria-hidden="true"></i>
            </span>
          </button>
        </div>
        <div class="dropdown-menu" id="dropdown-menu" role="menu">
          <div class="dropdown-content">
            <div class="dropdown-item">
              <%= form_tag(temp_form_path) do %>

                  <!-- SORTING CHECKBOXES -->
                  <div class="feed-left"> SORT BY: </div>
                  <div>
                      <%= check_box_tag(:upcoming) %>
                      <span class="small-tab checkboxes"> <%= label_tag(:mobile_upcoming, "Upcoming") %> </span> <br>
                      <%= check_box_tag(:highrated) %>
                      <span class="small-tab checkboxes"> <%= label_tag(:mobile_highrated, "Most Liked") %> </span>
                  </div>

                  <!-- FILTERS -->
                  <div class="feed-left"> FILTER BY: </div>
                  <div class="checkboxes">
                    <label><input name="freq" value="one-time" type="radio" class="radio-box"> <span class="small-tab">One-Time</span></input></label>
                    <span>&#160;</span>
                    <label><input name="freq" value="ongoing" type="radio" class="radio-box"> <span class="small-tab">Ongoing</span></input></label>
                    <br>
                    <label><input name="remo" value="in-person" type="radio" class="radio-box"> <span class="small-tab">In-Person</span></input></label>
                    <span>&#160;</span>
                    <label><input name="remo" value="remote" type="radio" class="radio-box"> <span class="small-tab">Remote</span> </input></label>
                  </div>

                  <!-- SLIDER -->
                  <div class="feed-left"> DISTANCE: </div>

                  <!-- <input id="distanceSlider" class="slider has-output is-fullwidth" min="0" max="30" value="30" step="1" type="range"> -->
                  <%= range_field_tag(:mobile_distance, @slider, min:0.5, max:15, step:0.1, class:"slider has-output is-fullwidth", id:"distanceblabla")%>
                  <p style="text-align:center">up to <output for="distanceblabla"><%= @slider %></output> miles away from:</p>
                    <div class="checkboxes">
                        <label><input name="location" value="loc1" type="radio" class="radio-box"><span class="small-tab"><%= Landmark.first.name %></span></label><br/>
                        <% if !Landmark.second.nil? %>
                            <label><input name="location" value="loc2" type="radio" class="radio-box"><span class="small-tab"><%= Landmark.second.name %></span></label><br/>
                        <% end %>
                        <% if !Landmark.third.nil? %>
                            <label><input name="location" value="loc3" type="radio" class="radio-box"><span class="small-tab"><%= Landmark.third.name %></span></label><br/>
                        <% end %>
                    </div>
                  <!-- TAGS -->
                  <div class="feed-left"> TAGS: </div>
                  <div class="tags tagbox">
                      <% Tag.all.each do |f| %>
                          <% if !@tags.nil? && @tags.include?(f.name) %>
                              <span class="tag is-rounded filter-custom-tag-mobile filter-custom-tag-checked-mobile" name=<%= f.name %> ><%= f.name %></span>
                          <% else %>
                              <span class="tag is-rounded filter-custom-tag-mobile" name=<%= f.name %> ><%= f.name %></span>
                          <% end %>
                      <% end %>
                  </div>

                  <div>
                      <div id="tagInputContainerMobile">
                          <%= submit_tag(" filter opportunities ", :class => "button filter-button is-centered is-fullwidth" ) %>
                          <% end %>
                      </div>
                  </div>
            </div>
          </div>
        </div>
      </div>
        <div class="column is-one-fifth column-feed is-hidden-mobile">

            <%= form_tag(temp_form_path) do %>

                <!-- SORTING CHECKBOXES -->
                <div class="feed-left"> SORT BY: </div>
                <div>
                    <%= check_box_tag(:upcoming) %>
                    <span class="small-tab checkboxes"> <%= label_tag(:upcoming, "Upcoming") %> </span> <br>
                    <%= check_box_tag(:highrated) %>
                    <span class="small-tab checkboxes"> <%= label_tag(:mobile_highrated, "Most Liked") %> </span>
                </div>

                <!-- FILTERS -->
                <div class="feed-left"> FILTER BY: </div>
                <div class="checkboxes">
                    <label><input name="freq" value="one-time" type="radio" class="radio-box"> <span class="small-tab">One-Time</span></input></label>
                    <span>&#160;</span>
                    <label><input name="freq" value="ongoing" type="radio" class="radio-box"> <span class="small-tab">Ongoing</span></input></label>
                    <br>
                    <label><input name="remo" value="in-person" type="radio" class="radio-box"> <span class="small-tab">In-Person</span></input></label>
                    <span>&#160;</span>
                    <label><input name="remo" value="remote" type="radio" class="radio-box"> <span class="small-tab">Remote</span> </input></label>
                </div>

                <!-- SLIDER -->
                <div class="feed-left"> DISTANCE: </div>

                <!-- <input id="distanceSlider" class="slider has-output is-fullwidth" min="0" max="30" value="30" step="1" type="range"> -->
                <%= range_field_tag(:distance, @slider, min:0.5, max:15, step:0.1, class:"slider has-output is-fullwidth", id:"distanceSlider")%>
                <p style="text-align:center">up to <output for="distanceSlider"><%= @slider %></output> miles away from:</p>
                  <div class="checkboxes">
                      <label><input name="location" value="loc1" type="radio" class="radio-box"><span class="small-tab"><%= Landmark.first.name %></span></label><br/>
                      <% if !Landmark.second.nil? %>
                        <label><input name="location" value="loc2" type="radio" class="radio-box"><span class="small-tab"><%= Landmark.second.name %></span></label><br/>
                      <% end %>
                      <% if !Landmark.third.nil? %>
                        <label><input name="location" value="loc3" type="radio" class="radio-box"><span class="small-tab"><%= Landmark.third.name %></span></label><br/>
                      <% end %>
                  </div>
                <!-- TAGS -->
                <div class="feed-left"> TAGS: </div>
                <div class="tags tagbox">
                    <% Tag.all.each do |f| %>
                        <% if !@tags.nil? && @tags.include?(f.name) %>
                            <span class="tag is-rounded filter-custom-tag filter-custom-tag-checked" name=<%= f.name %> ><%= f.name %></span>
                        <% else %>
                            <span class="tag is-rounded filter-custom-tag" name=<%= f.name %> ><%= f.name %></span>
                        <% end %>
                    <% end %>
                </div>

                <div>
                    <div id="tagInputContainer">
                        <%= submit_tag(" filter opportunities ", :class => "button filter-button is-centered is-fullwidth" ) %>
                        <% end %>
                    </div>
                </div>

                </br>

                <!--
                <div class="buttons is-centered saved">
                    <%= link_to '<i class="fas fa-user-check"></i><span class="small-tab">view sign ups</span>'.html_safe, temp_form_path( signed_up: 1), class: "button is-small feed-saved-button" %>
                    <%= link_to '<i class="fas fa-history"></i><span class="small-tab">view volunteer history</span>'.html_safe, temp_form_path( history: 1), class: "button is-small feed-saved-button" %>
                </div>
                -->
        </div>

        <div class="column column-feed">
            <div id="back-to-top"></div>
            <div id="link-wrap" >
                <%= render @opportunities %>
            </div>
            <br>
             <% if @opportunities.next_page %>
                <div class="link buttons is-centered">
                    <div class="more">
                        <%= link_to 'Load More', feed_volunteer_path(:page => @opportunities.next_page), :class => "next_page button page-button", :remote => true if @opportunities.next_page %>
                    </div>
                    <a href="#back-to-top" class="button page-button"> <i class="fas fa-angle-double-up" style="margin: 0 5px 0 0;"></i> Back to top </a>
                </div>
            <% end %>
        </div>

    </div>
</body>

</html>

<script>
    function findOutputForSlider(el) {
        var idVal = el.id;
        outputs = document.getElementsByTagName('output');
        for( var i = 0; i < outputs.length; i++ ) {
        if (outputs[i].htmlFor == idVal)
            return outputs[i];
        }
    }

    function updateSliderValue() {
        var sliders = document.querySelectorAll( 'input[type="range"].slider' );
        [].forEach.call( sliders, function ( slider ) {
        var output = findOutputForSlider( slider );
        if ( output ) {
            slider.addEventListener( 'input', function( event ) {
            output.value = event.target.value;
            } );
        }
        } );
    }

    updateSliderValue();

    var dropdown = document.querySelector('.dropdown');
    var button = document.querySelector('.dropdown-trigger');
    button.addEventListener('click', function(event) {
      event.stopPropagation();
      dropdown.classList.toggle('is-active');
      updateSliderValue();
    });
</script>

app/views/dashboard/history.js.erb
$("#tab-display").html("<%= escape_javascript(render partial: 'history') %>");
$(".custom-tab-selected").css("color", "rgb(181,181,181)");
$(".custom-tab").css("color", "rgb(181,181,181)");
$(".custom-tab-third").css("color", "rgb(19,35,87)");

app/views/dashboard/hours.js.erb
$("#tab-display").html("<%= escape_javascript(render partial: 'hour') %>");
$(".custom-tab-selected").css("color", "rgb(19,35,87)");
$(".custom-tab").css("color", "rgb(181,181,181)")
$(".custom-tab-third").css("color", "rgb(181,181,181)")

app/views/dashboard/profile_volunteer.html.erb
<!-- problems to fix or consider:
age affilication location arent really scalable
-->

<!DOCTYPE html>
<html class="grey-background">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello Bulma!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    </head>

    <body>
        <!-- navigation bar -->
        <%= render "layouts/navbar"%>
        

        <!-- columns (first/left column is profile, second/right column is section with stats, notifs,
        volunteers tabs) -->
        <div class="columns">
            <div class="column is-one-third column-profile-left">
                <section class="profile-volunteer-section">
                    <div>
                        <figure class="image has-image-centered">
                            <% if !current_user.pictures.nil? && !current_user.pictures.find_by_name("User#{current_user.id}pfp").nil? %>
                                <%= image_tag current_user.pictures.find_by_name("User#{current_user.id}pfp").image.url, class: "is-rounded  profile-volunteer-pic" %>
                            <% else %>
                                <%= image_tag "placeholder_profile.png", :class => "profile-volunteer-pic" %>
                            <% end %>
                        </figure>
                    </div>
                    <div class="profile-title">
                        <div> <%= current_user.name.titleize %>
                            <%= link_to edit_user_path(id: current_user.id) do %>
                                <span class="settings-icon"> <i class="fas fa-cog"></i> </span>
                            <% end %>
                        </div>
                    </div>
                </section>

                <div class="profile-contact">
                    <div> <i class="far fa-envelope"></i> <%= mail_to current_user.email %> </div>
                    <div> <i class="far fa-clock"></i> <%= current_user.total_hours(current_user)["Completed"] %> hours volunteered </div>
                </div>
                <div class="profile-description">
                    <%= current_user.description.html_safe unless current_user.description.nil?  %>
                </div>
                <div class="profile-columns">
                    <div class="columns is-centered is-gapless  vol-profile-col">
                        <div class="column is-half">
                            <div class="profile-left-info">
                                AFFILIATION
                            </div>
                        </div>
                        <div class="column is-half">
                            <div class="profile-right-info">
                                <%= current_user.affiliation %>
                            </div>
                        </div>
                    </div>
                    <div class="columns is-centered is-gapless vol-profile-col">
                        <div class="column is-half">
                            <div class="profile-left-info">
                                <% case current_user.affiliation %>
                                <% when "Undergraduate student" %>
                                    MAJOR
                                <% when "Graduate/professional student" %>
                                    SCHOOL
                                <% when "Alumni" %>
                                    DEGREE
                                <% else %>
                                    DEPARTMENT
                                <% end %>
                            </div>
                        </div>
                        <div class="column is-half">
                            <div class="profile-right-info">
                                <% case current_user.affiliation %>
                                <% when "Undergraduate student" %>
                                    <%= current_user.major %>
                                <% when "Graduate/professional student" %>
                                    <%= current_user.school %>
                                <% when "Alumni" %>
                                    <%= current_user.degree %>
                                <% else %>
                                    <%= current_user.department %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <div class="columns is-centered is-gapless vol-profile-col">
                        <div class="column is-half">
                            <div class="profile-left-info">
                                LOCATION
                            </div>
                        </div>
                        <div class="column is-half">
                            <div class="profile-right-info">
                                <%= current_user.address.printable_address unless current_user.address.nil? %>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="tags are-medium">
                        <% current_user.tags.each do |f| %>
                            <span class="tag is-rounded custom-tag"><%= f.name %></span>
                        <% end %>
                    </div>
                </div>
                <br>

                <% if user_signed_in? %>
                    <div id="navbarAuth">
                        <div style="float: right;">
                            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item button sign-in-button'  %>
                        </div>
                    </div>
                <% end %>
                <br>
            </div>

            <!-- hours page -->

            <div class="column column-profile-right">
                <div class="tabs is-centered tabs-bar">
                    <ul>
                        <li><%= link_to 'hours', hours_path, :remote => true, class: "custom-tab-blue custom-tab-selected" %></li>
                        <li><%= link_to 'notifications', notifs_path, :remote => true, class: "custom-tab" %></li>
                        <li><%= link_to 'history', history_path, :remote => true, class: "custom-tab-third" %></li>
                    </ul>
                </div>

                <div id="tab-display" >
                    <%= render 'hour' %>
                </div>


            </div>
        </div>

    </body>
</html>