config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "dashboard#index"
  get "/customize_complete" => "dashboard#customize_complete", as: "customize_interface"
  post "/customize_complete" => "dashboard#customize_complete", as: "customize_interface_form"
  get "/error404" => "dashboard#error404"
  get "/error500" => "dashboard#error500"
  get "/error403" => "dashboard#error403"
  get 'opportunities' => 'opportunities#index'
  get "/profile_volunteer" => "dashboard#profile_volunteer"
  #get "/profile_organization" => "organization#profile_organization"

  resources :organization
  get "/hours" => "dashboard#hours", as: "hours"
  get "/notifs" => "dashboard#notifs", as: "notifs"
  get "/history" => "dashboard#history", as: "history"
  get "/notifications" => "organization#notifications", as: "notifications"
  get "/stats/:id" => 'organization#stats', as: "stats"
  get "/volunteers/:id" => 'organization#volunteers', as: "volunteers"
  get "/reviews/:id" => 'organization#reviews', as: "reviews"
  get "/histories/:id" => 'organization#histories', as: "histories"
  get "/opps/:id" => 'organization#opps', as: "opps"
  get "/opportunities/:id/clone" => 'opportunities#clone', as: "clone_opportunity"
  post 'organization/approve'
  post 'organization/deny'

  resources :challenges
  get "/stat" => "admin#statistics"
  get "/requests" => "admin#requests"
  get "/organizations" => "admin#organizations"
  get "/goals" => "admin#goals"

  resources :opportunities
  get "/secret" => "organization#secret"
  get '/auth/duke-oauth2/callback', to: 'dashboard#create'
  get "/feed_volunteer" => "dashboard#feed_volunteer"
  post "/feed_volunteer" => "dashboard#feed_volunteer", as: "temp_form"
  post "/feed_organization" => "organization#feed_organization", as: "org_form"
  get "/feed_organization" => "organization#feed_organization"
  get "/admin" => "admin#admin_home"
  #get "/posting_volunteer" => "dashboard#posting_volunteer"
  get "/opportunities/:id/contact_volunteers" => "opportunities#contact_volunteers", as: "contact_volunteers"
  post "/opportunities/:id/contact" => "opportunities#contact", as: "contact_path"
  get "/opportunities/:id/view_volunteers" => "opportunities#view_volunteers", as: "view_volunteers"
  get "/organization/:id/like" => "organization#like", as: "like_action"
  get "/opportunities/:id/like" => "opportunities#like", as: "like_action_opportunity"

  get "/admin_home" => "admin#admin_home"
  get "/admin_settings" => "admin#admin_settings", as: "admin_settings"
  patch "/admin_home" => "admin#update_settings", as: "update_settings"
  post "/admin_home" => "admin#update_admin", as: "admin_form"
  
  get "/onboard" => "onboarding#onboard"
  get "/volunteer_partial" => "onboarding#volunteer_partial"
  get "/organization_partial" => "onboarding#organization_partial"
  get "/complete" => "onboarding#complete", as: "onboarding_complete"
  post "/complete" => "onboarding#complete", as: "onboarding_complete_form"
  post 'admin/approve'
  post 'admin/deny'

  get "/edit_user/:id" => "dashboard#edit_user", as: "edit_user"
  patch "/profile_volunteer" => "dashboard#update_user", as: "update_user"
  resources :dashboard, only: [:show]

  get "/edit_custom/:id" => "organization#edit_custom", as: "edit_custom"

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/views/admin/_goal.html.erb
<div class="column is-8 is-offset-2">
    <%= link_to "Create new challenge!", new_challenge_path, class: "button add-challenge-button is-centered is-fullwidth" %>
</div>

<div class ="column is-8 is-offset-2">
    <div class="org-master-container">
        <% Challenge.all.each do |challenge| %>
            <div class="admin-orgs columns is-mobile">
                <div class="column">
                    <div class="admin-challenge-name"> <%= challenge.title %> (<%= challenge.goal %> hours)</div>
                    <div class="admin-challenge-date"> <%= challenge.start %> - <%= challenge.end %> </div>
                    <div class="admin-challenge-info"> <%= challenge.description.html_safe %> </div>
                    <%= link_to '<button class="challenges-edit-button button">edit challenge</button>'.html_safe, edit_challenge_path(challenge) %> <br><br>
                    <%= link_to '<div class="challenges-delete">or delete this challenge</div>'.html_safe, challenge_path(challenge), method: :delete, data: {confirm: "Are you sure you want to delete this challenge?"} %><br>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/_organization.html.erb
<div class="org-master-container">
    <% Organization.all.each do |org| %>
        <div class="admin-orgs columns is-mobile">
            <div class="column is-narrow is-hidden-mobile">
                <figure class="image is-96x96 has-image-centered">
                    <% if !org.pictures.nil? && !org.pictures.find_by_name("Org#{org.id}pfp").nil? %>
                        <%= image_tag org.pictures.find_by_name("Org#{org.id}pfp").image.url, style:"object-fit: cover;" %>
                    <% else %>
                        <img class="profile-volunteer-pic" src="https://bulma.io/images/placeholders/128x128.png">
                    <% end %>
                </figure>
            </div>
            <div class="column">
                <div class="admin-org-name"> <%= org.name %> </div>
                <div class="admin-org-info"> <%= org.email %> </div>
                <div class="admin-org-info"> <%= org.phone %> </div>
                <div class="admin-org-info"> <%= org.addresses.first.printable_address() unless org.addresses.first.nil? %> </div>
                <%= link_to '<button class="profile-notif-button button">view</button>'.html_safe, organization_path(org) %>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/_request.html.erb
<div class="profile-notifications">
  <% if @notifications.empty? %>
    <div class="notification">
      No notifications yet.
    </div>
  <% else %>
    <% @notifications.each do |notif| %>
        <div class="notification">
            <% if notif.actor.approved.nil? %>
              <div class="columns">
                <div class="column is-2">
                  <figure class="image has-image-centered">
                    <% if !notif.notifiable.pictures.nil? && !notif.notifiable.pictures.find_by_name("Org#{notif.notifiable.id}pfp").nil? %>
                      <%= image_tag notif.notifiable.pictures.find_by_name("Org#{notif.notifiable.id}pfp").image.url, class: "requests-org-pic" %>
                    <% else %>
                      <img class="requests-org-pic" src="https://bulma.io/images/placeholders/128x128.png">
                    <% end %>
                  </figure>
                </div>
                <div class="column">
                  <span class="notif-org-name">
                    <%= notif.actor.organization.name unless notif.actor.organization.nil? %>
                    <%= "#{notif.action.humanize(capitalize: false)}:" %></br>
                  </span> 

                  <span class="notif-text">
                  This request was made by <%= notif.actor.name %>
                  <%= "(#{notif.actor.position})." unless notif.actor.position.blank? %> <br>
                  You may contact them at <%= notif.actor.email %> 
                  <%= "or #{notif.actor.phone}." unless notif.actor.phone.blank? %> <br>

                  <%= notif.actor.organization.name %>: <br>
                  </span>
                  <span class="tab notif-text">
                    This organization is<%= " not" unless notif.actor.organization.registered == true %> registered with the with the Triangle Nonprofit & Volunteer Leadership Center. </br>
                    
                    <% if !notif.actor.organization.email.blank? %>
                      Email: <%= notif.actor.organization.email %> <br>
                    <% end %>

                    <% if !notif.actor.organization.website.blank? %>
                      Website: <%= notif.actor.organization.website %> <br>
                    <% end %>

                    <% if !notif.actor.organization.addresses.first.blank? %>
                      Address: <%= notif.actor.organization.addresses.first.printable_address %> <br>
                    <% end %>

                    <% if !notif.actor.organization.ein.blank? %>
                      Nonprofit EIN: <%= notif.actor.organization.ein %> <br>
                    <% end %>

                    <% if !notif.actor.organization.description.blank? %>
                      Description: <%= notif.actor.organization.description %> <br>
                    <% end %>
                  </span>
                  <div class="admin-buttons">
                    <span class="button admin-cancel-button">
                      <%= link_to "deny", {:controller => 'admin', :action => "deny", notif: notif }, :method => :post %>
                    </span>
                    <span class="button admin-submit-button">
                      <%= link_to "approve", {:controller => 'admin', :action => "approve", notif: notif }, :method => :post %>
                    </span>
                  </div>
                  </br></br>
                </div>
                </div>
            <% elsif notif.actor.approved %>
              <div class="profile-notification-blue-dark">
                <%= notif.actor.organization.name %> has been approved.
              </div>
              <div class="notif-org-info">
                This request was made by <%= notif.actor.name %>. <br> You may contact them at <%= notif.actor.email %>.
              </div>
            <% else %>
              <div class="profile-notification-blue-dark">
                <%= notif.actor.organization.name %> has been denied.
              </div>
              <div class="notif-org-info">
                This request was made by <%= notif.actor.name %>. <br> You may contact them at <%= notif.actor.email %>.
              </div>
            <% end %>
          </div>
      <% end%>
  <% end %>
</div>

app/views/admin/_stat.html.erb
<div class="grey-stat">
<span class="bold-stat"><%= Opportunity.hours_this_week %></span> hours of service logged this week.
</div>
<div class="white-stat">
<span class="bold-stat"><%= Opportunity.hours_this_month %></span> hours of service logged this month.
</div>
<div class="grey-stat">
There are <span class="bold-stat"><%= User.count %></span> volunteers on <%= @interface.name %>
</div>
<div class="white-stat">
There are <span class="bold-stat"><%= Organization.count %></span> organizations registered on <%= @interface.name %>.
</div>
<div class="grey-stat">
    There are <span class="bold-stat"><%= $opportunities_available %></span> upcoming opportunities.
</div>
<div class="white-stat">
    There are <span class="bold-stat"><%= $positions_available %></span> volunteering positions available.
</div>
<div class="grey-stat">
    There are <span class="bold-stat"><%= $positions_filled %></span> volunteering positions filled.
</div>
<hr>

<div class="hours-container">
    <div>
        <div class="field has-addons graph-bar-tabs">
            <p class="control">
                <button class="button is-light" id="weekly-button">
                    Week
                </button>
            </p>
            <p class="control">
                <button class="button" id="yearly-button">
                    Year
                </button>
            </p>
        </div>
        <h3 style="text-align: center;"> Total hours recorded<h3>
    </div>
    <br>
    <div id="weekly-hours-graph">
        <p class="graph-text">This graph shows the total amount of hours logged by volunteers in the last 8 weeks.</p>
        <%= column_chart $weekly_stats, ytitle: "Hours", xtitle: "Week", colors: [ '#132357'], download: true, download: {filename: "total_hours_weekly_#{Date.today.to_s}"} %>
    </div>
    <div id="yearly-hours-graph" style="display: none">
        <p class="graph-text">This graph shows the total amount of hours logged by volunteers in the last 12 months.</p>
        <%= column_chart $monthly_stats, ytitle: "Hours", xtitle: "Month", colors: [ '#132357'], download: true, download: {filename: "total_hours_yearly_#{Date.today.to_s}"} %>
    </div>
    <hr>
</div>

<div class="pie-container">
    <h3 style="text-align: center;"> Total hours recorded per tag<h3>
    <p class="graph-text", style="text-align: center !important;">These donut charts show the most popular tags on the hours logged in the last week, month, and year</p>
    <div class="pie-chart-container">
        <div class="pie-chart">
            <%= pie_chart $opptagsweek, donut: true, colors: [ 'b5b5b5', '#c84e00', '#d9740c',
            '#e89923','#f4b941', '#ffd960', '#8FD170', '#00BC9C', '#009CBA', '#0577B1',
            '#114B85', '#132357'], legend: false, title: "This week", messages: {empty: "No data yet"}, download: true, download: {filename: "tags_donut_week_#{Date.today.to_s}"} %>
        </div>
        <div class="pie-chart">
            <%= pie_chart $opptagsmonth, donut: true, colors: [ 'b5b5b5', '#c84e00', '#d9740c',
            '#e89923','#f4b941', '#ffd960', '#8FD170', '#00BC9C', '#009CBA', '#0577B1',
            '#114B85', '#132357'], legend: false, title: "This month",  messages: {empty: "No data yet"}, download: true, download: {filename: "tags_donut_month_#{Date.today.to_s}"} %>
        </div>
        <div class="pie-chart">
            <%= pie_chart $opptagsyear, donut: true, colors: [ 'b5b5b5', '#c84e00', '#d9740c',
            '#e89923','#f4b941', '#ffd960', '#8FD170', '#00BC9C', '#009CBA', '#0577B1',
            '#114B85', '#132357'], legend: false, title: "This year", messages: {empty: "No data yet"}, download: true, download: {filename: "tags_donut_year_#{Date.today.to_s}"} %>
        </div>
    </div>
    <hr>
</div>
<!-- <%= line_chart $opp_tag_trend.map { |tag|
    {name: tag[0], data: tag[1]}
}, ytitle: "Hours", xtitle: "Month", title: "Trends in hours logged for each tag",
height: "600px", colors: [ 'b5b5b5', '#c84e00', '#d9740c', '#e89923','#f4b941', '#ffd960',
'#8FD170', '#00BC9C', '#009CBA', '#0577B1', '#114B85', '#132357'].reverse, curve: false, download: true %>
</br> -->
<div class="bar-container">
    <div>
        <div class="field has-addons graph-bar-tabs">
            <p class="control">
                <button class="button is-light" id="amount-button">
                    Total
                </button>
            </p>
            <p class="control">
                <button class="button" id="percentage-button">
                    Percentage
                </button>
            </p>
        </div>
        <h3 style="text-align: center;">Make-up of tags in logged hours<h3>
    </div>
    <br>
    <div id="amount-bar">
        <p class="graph-text">This graph shows the amount of hours logged for each month, grouped by its tags.
        Click on a tag's name to remove it from the graph.</p>
        <%= column_chart $opp_tag_trend.map {|tag|
            {name: tag[0], data: tag[1]}
        }, stacked: true, height: "500px", colors: [ 'b5b5b5', '#c84e00', '#d9740c', '#e89923',
        '#f4b941', '#ffd960', '#8FD170', '#00BC9C', '#009CBA', '#0577B1', '#114B85', '#132357'].reverse,
        ytitle: "Hours", xtitle: "Month", download: true, download: {filename: "tags_total_makeup_#{Date.today.to_s}"} %>
    </div>
    <div id="percentage-bar" style="display: none;">
        <p class="graph-text">This graph shows the percentage make-up of each tag in the hours logged the past 12 months.</p>
        <%= column_chart $opp_tag_percs.map {|tag|
            {name: tag[0], data: tag[1]}
        }, stacked: true, height: "500px", colors: [ 'b5b5b5', '#c84e00', '#d9740c', '#e89923',
        '#f4b941', '#ffd960', '#8FD170', '#00BC9C', '#009CBA', '#0577B1', '#114B85', '#132357'].reverse,
        suffix: "%", round: 2, max: 100, ytitle: "Percentage", xtitle: "Month", download: true, download: {filename: "tags_percentage_makeup_#{Date.today.to_s}"} %>
    </div>
</div>

app/views/admin/admin_home.html.erb
<!DOCTYPE html>
<html class="grey-background">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello Bulma!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    </head>

    <body>

    <!-- navigation bar -->
    <%= render "layouts/navbar" %>

    <div class="tabs is-right" style="padding-bottom: 0; margin-bottom: 0;">
    <h1 class="admin-name"> <%= current_user.name %> </h1>
        <ul class="custom-admin-nav">
            <li><a class="admin-nav-item admin-nav-active" id="stats-tab"> stats </a></li>
            <li><a class="admin-nav-item admin-nav-inactive" id="requests-tab"> requests </a></li>
            <li><a class="admin-nav-item admin-nav-inactive" id="orgs-tab"> organizations </a></li>
            <li><a class="admin-nav-item admin-nav-inactive" id="goals-tab"> challenges </a></li>
        </ul>
    </div>

    <!--THIS IS WHERE THE STATS START-->
    <div class="columns" style="padding-top: 0;">
        <div class="column admin-profile">
            <div id="tab-display">
                <%= render partial: 'stat'%>
            </div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item button sign-in-button is-hidden-tablet'  %>
        </div>
    </div>

    <% if user_signed_in? %>
        <div>
            <a role="button" onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            </a>
        </div>
    <% end %>
    </body>
</html>