config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "dashboard#index"
  get "/customize_complete" => "dashboard#customize_complete", as: "customize_interface"
  post "/customize_complete" => "dashboard#customize_complete", as: "customize_interface_form"
  get "/error404" => "dashboard#error404"
  get "/error500" => "dashboard#error500"
  get "/error403" => "dashboard#error403"
  get 'opportunities' => 'opportunities#index'
  get "/profile_volunteer" => "dashboard#profile_volunteer"
  #get "/profile_organization" => "organization#profile_organization"

  resources :organization
  get "/hours" => "dashboard#hours", as: "hours"
  get "/notifs" => "dashboard#notifs", as: "notifs"
  get "/history" => "dashboard#history", as: "history"
  get "/notifications" => "organization#notifications", as: "notifications"
  get "/stats/:id" => 'organization#stats', as: "stats"
  get "/volunteers/:id" => 'organization#volunteers', as: "volunteers"
  get "/reviews/:id" => 'organization#reviews', as: "reviews"
  get "/histories/:id" => 'organization#histories', as: "histories"
  get "/opps/:id" => 'organization#opps', as: "opps"
  get "/opportunities/:id/clone" => 'opportunities#clone', as: "clone_opportunity"
  post 'organization/approve'
  post 'organization/deny'

  resources :challenges
  get "/stat" => "admin#statistics"
  get "/requests" => "admin#requests"
  get "/organizations" => "admin#organizations"
  get "/goals" => "admin#goals"

  resources :opportunities
  get "/secret" => "organization#secret"
  get '/auth/duke-oauth2/callback', to: 'dashboard#create'
  get "/feed_volunteer" => "dashboard#feed_volunteer"
  post "/feed_volunteer" => "dashboard#feed_volunteer", as: "temp_form"
  post "/feed_organization" => "organization#feed_organization", as: "org_form"
  get "/feed_organization" => "organization#feed_organization"
  get "/admin" => "admin#admin_home"
  #get "/posting_volunteer" => "dashboard#posting_volunteer"
  get "/opportunities/:id/contact_volunteers" => "opportunities#contact_volunteers", as: "contact_volunteers"
  post "/opportunities/:id/contact" => "opportunities#contact", as: "contact_path"
  get "/opportunities/:id/view_volunteers" => "opportunities#view_volunteers", as: "view_volunteers"
  get "/organization/:id/like" => "organization#like", as: "like_action"
  get "/opportunities/:id/like" => "opportunities#like", as: "like_action_opportunity"

  get "/admin_home" => "admin#admin_home"
  get "/admin_settings" => "admin#admin_settings", as: "admin_settings"
  patch "/admin_home" => "admin#update_settings", as: "update_settings"
  post "/admin_home" => "admin#update_admin", as: "admin_form"
  
  get "/onboard" => "onboarding#onboard"
  get "/volunteer_partial" => "onboarding#volunteer_partial"
  get "/organization_partial" => "onboarding#organization_partial"
  get "/complete" => "onboarding#complete", as: "onboarding_complete"
  post "/complete" => "onboarding#complete", as: "onboarding_complete_form"
  post 'admin/approve'
  post 'admin/deny'

  get "/edit_user/:id" => "dashboard#edit_user", as: "edit_user"
  patch "/profile_volunteer" => "dashboard#update_user", as: "update_user"
  resources :dashboard, only: [:show]

  get "/edit_custom/:id" => "organization#edit_custom", as: "edit_custom"

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :addresses, as: :locatable
    has_many :opportunities
    has_many :pictures, as: :imageable
    has_many :users
    has_and_belongs_to_many :organizations
    has_and_belongs_to_many :ratings
    has_many :feedbacks
    
    def volunteer_list()
        volunteers = []
        self.opportunities.all.each do |f|
            (volunteers.concat(f.users.all)).uniq
        end
        volunteers
    end

    def hours_during(start_date, end_date)
        hrs = 0
        self.opportunities.all.each do |opportunity|
            if opportunity.date >= start_date && opportunity.date < end_date
                hrs += opportunity.hours * opportunity.users.count
                hrs += opportunity.archived_opportunities.all.pluck(:hours).sum
            end
        end
        hrs
    end

    def weekly_volunteers()
        start_date = (Date.today - Date.today.wday).to_time.to_i
        end_date = Time.now.to_i
        volunteers = 0
        self.opportunities.all.each do |opportunity|
            if opportunity.date >= start_date && opportunity.date < end_date
                volunteers += opportunity.users.count
                volunteers += opportunity.archived_opportunities.all.count
            end
        end
        volunteers
    end

    def hours_this_week()
        start_date = (Date.today - Date.today.wday).to_time.to_i
        end_date = Time.now.to_i
        hrs = 0
        self.opportunities.all.each do |opportunity|
            if opportunity.date >= start_date && opportunity.date < end_date
                hrs += opportunity.hours * opportunity.users.count
                hrs += opportunity.archived_opportunities.all.pluck(:hours).sum
            end
        end
        hrs
    end
end 

app/controllers/organization_controller.rb
class OrganizationController < ApplicationController

    # any line with 'if Interface.first.nil? redirect to root_url and return' ensures that the user is taken to the
    # homescreen and asked to create/customize an interface if it doesn't already exist (usually occurs with initial build)

    before_action :check_auth

    def secret
        if Interface.first.nil?
            redirect_to root_url and return
        end
    end

    # Remove this method later
    def profile_organization
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @opportunities = Opportunity.all.org_opps(current_user)
        @organization = current_user.organization

        $weekly_stats = Hash.new
        for i in 0..4
            date = Date.today - Date.today.wday + (4 * (i - 4))
            week_hours = @organization.hours_during(date.to_time.to_i, (date + 7).to_time.to_i)
            $weekly_stats[date.strftime("%b %d") + " - " + (date + 6).strftime("%b %d")] = week_hours
        end

        $monthly_stats = Hash.new
        for i in 0..5
            date = 1.year.ago.at_beginning_of_month.to_time + i.month
            month_hours = @organization.hours_during(date.to_time.to_i, (date + 1.month).to_time.to_i)
            $monthly_stats[date.strftime("%b")] = month_hours
        end
    end

    def feed_organization
        if Interface.first.nil?
            redirect_to root_url and return
        end
        @interface = Interface.first

        #Var to determine navbar link colors
        @ifFeed = true
        unless current_user.is_a?(OrgAdmin) || current_user.admin == true
            redirect_to "/error403"
        end

        #checks location to filter by
    if !params[:location].nil?
        $location = Landmark.first if params[:location] == "loc1"
        $location = Landmark.second if params[:location] == "loc2"
        $location = Landmark.third if params[:location] == "loc3"
      else
        $location = Landmark.first
      end

        if params[:tags].nil?
            @tags = params[:mobile_tags]
        else
            @tags = params[:tags]
        end

        if params[:distance].nil?
            @slider = 15
        else
            @slider = params[:distance]
        end

        if params[:page].nil?
            $opportunities = Opportunity.sorting_opps(!params[:upcoming].to_i.zero?,
                !params[:highrated].to_i.zero?, params[:freq], params[:remo], params[:distance], 
                params[:location], @tags, true, current_user).distinct
        end

        $opportunities = $opportunities.paginate(:page => params[:page], :per_page => 5)
        @organizations = Organization.all
        @opportunities = $opportunities


        respond_to do |format|
            format.html
            format.js
        end
    end

    # Render notifications
    def notifications
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @notifications = Notification.where(recipient: current_user).reverse
        respond_to do |format|
            format.js {render layout: false}
        end
    end

    # Render stats
    def stats
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find_by_id(params[:id])
        respond_to do |format|
            format.js {render layout: false}
        end
    end

    # Render list of volunteers
    def volunteers
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find_by_id(params[:id])
        respond_to do |format|
            format.js {render layout: false}
        end
    end

    # Render history
    def histories
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find_by_id(params[:id])
        respond_to do |format|
            format.js {render layout: false}
        end
    end

    # Render opportunities
    def opps
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find_by_id(params[:id])
        respond_to do |format|
            format.js {render layout: false}
        end
    end

    # Render reviews
    def reviews
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find_by_id(params[:id])
        respond_to do |format|
            format.js {render layout: false}
        end
    end

    def new
        if Interface.first.nil?
            redirect_to root_url and return
        end
        @organization = Organization.new
    end

    def create
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.new(organization_params)
        @organization.save

        redirect_to @organization
    end

    # Liking system of organization
    def like
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find(params[:id])

        if !params[:like].nil? && !@organization.ratings.include?(Rating.find_by(user_id: current_user.id))
            if current_user.ratings.first.nil?
                rating = Rating.new(name:current_user.name)
                current_user.ratings << rating
            else
                rating = current_user.ratings.first
            end
            @organization.ratings << rating
        elsif !params[:like].nil?
            @organization.ratings.delete(Rating.find_by(user_id: current_user.id))
        end

        redirect_to @organization
    end

    def show
        @ifDashboard = true
        if Interface.first.nil?
            redirect_to root_url and return
        end
        @interface = Interface.first


        @organization = Organization.find(params[:id])

        $weekly_stats = Hash.new
        for i in 0..4
            date = Date.today - Date.today.wday + (4 * (i - 4))
            week_hours = @organization.hours_during(date.to_time.to_i, (date + 7).to_time.to_i)
            $weekly_stats[date.strftime("%b %d") + " - " + (date + 6).strftime("%b %d")] = week_hours
        end

        $monthly_stats = Hash.new
        for i in 0..5
            date = 1.year.ago.at_beginning_of_month.to_time + i.month
            month_hours = @organization.hours_during(date.to_time.to_i, (date + 1.month).to_time.to_i)
            $monthly_stats[date.strftime("%b")] = month_hours
        end

        respond_to do |format|
            format.html
            format.js
        end
    end

    def edit_custom
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = current_user.organization
    end

    def update
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find(params[:id])

        if(update_params)
            redirect_to @organization
        else
            render 'edit'
        end
    end

    def destroy
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = Organization.find(params[:id])
        @organization.destroy
        redirect_to organization_path
    end

    def approve
        if Interface.first.nil?
            redirect_to root_url and return
        end

      n = Notification.find_by(id: params[:notif])
      n.actor.update_attribute(:approved, true)
      UserMailer.approved_org_adm(n.actor.email, n.actor.organization.name).deliver_now
    end

    def deny
        if Interface.first.nil?
            redirect_to root_url and return
        end

      n = Notification.find_by(id: params[:notif])
      n.actor.update_attribute(:approved, false)
      UserMailer.denied_org_adm(n.actor.email, n.actor.organization.name).deliver_now
    end

    private def organization_params
        if Interface.first.nil?
            redirect_to root_url and return
        end

        params.require(:organization).permit(:name, :description, :location, :website, :email, :phone)
    end

    private def update_params
        if Interface.first.nil?
            redirect_to root_url and return
        end

        current_user.update(name: params[:org_admin][:username],
            position: params[:org_admin][:position], phone: params[:org_admin][:phone])

        if @organization.addresses.first.blank?
            if !params[:org_admin][:street].nil?
              @organization.addresses.build(street: params[:org_admin][:street],
                city: params[:org_admin][:city], state: params[:org_admin][:state], zip: params[:org_admin][:zip])
              @organization.save
            end
        else
            @organization.addresses.first.update(street: params[:org_admin][:street],
                city: params[:org_admin][:city], state: params[:org_admin][:state], zip: params[:org_admin][:zip])
        end

        @organization.update(name: params[:org_admin][:name], website: params[:org_admin][:website],
            phone: params[:org_admin][:org_phone], email: params[:org_admin][:email], description: params[:description],
            location: @organization.addresses.first.printable_address)

        #Adding profile pic
        if !params[:org_admin][:profile_pic].nil?
            if !@organization.pictures.nil? && !@organization.pictures.find_by_name("User#{@organization.id}pfp").nil?
                current_pfp = @organization.pictures.find_by_name("Org#{@organization.id}pfp")
                current_user.pictures.delete(current_pfp)
                Picture.delete(current_pfp)
            end
            pfp = Picture.new(name: "Org#{@organization.id}pfp", imageable_id: @organization.id,
                imageable_type: "#{@organization.class}")
            pfp.image = params[:org_admin][:profile_pic]
            pfp.save!

app/views/organization/_history.html.erb
<div class="profile-notifications">
    <div class="notification">
        <span class="profile-notification-blue-dark"> <%= @organization.volunteer_list().length() %> </span> people have volunteered for this organization
    </div>

    <% current_user.feedbacks.reverse.each do |feedback| %>
        <% if feedback.organization == @organization %>

        <div class="notification">

            You left a review for this organization on <%= feedback.created_at.strftime("%a, %b %d, %Y") %>. This was for 
            <span class="profile-notification-pink"><%= feedback.opportunity.title %></span>
            <% if !feedback.opportunity.ongoing %>
              <%= " that happened on " + feedback.opportunity.display_date_pretty(feedback.opportunity.date) %>
            <% end %>
            </br>
            </br>

            This is what you said: </br>
            <span style="font-style: italic"><%= feedback.description %></span>
        </div>

      <% end %>
    <% end %>
    
</div>

app/views/organization/_notif.html.erb
<div class="profile-notifications">
  <% if @notifications.empty? %>
    <div class="notification">
      No notifications yet.
    </div>
  <% else %>
    <% @notifications.each do |notif| %>
    <div class='notification'>
      <% if notif.notifiable.class == Opportunity %>
        <%= "#{notif.actor.name} #{notif.action.humanize(capitalize: false)} an #{notif.notifiable.class.to_s.underscore.humanize.downcase}"  %>
        <span class='profile-notification-blue-dark'><%= notif.notifiable.title %></span>
        <% if notif.notifiable.require_approvals? && notif.action == "has_signed_up_for"%>
          Please visit "View Volunteers" in your opportunity's page to manage approvals.
        <% end %>
        <a class='profile-notif-arrow' href=<%=opportunity_path(notif.notifiable, anchor: dom_id(notif.notifiable))%>> <i class='fas fa-arrow-circle-right'></i></a>
      <% elsif notif.notifiable.class == Organization %>
        <% if notif.actor.approved.nil? %>
          <%= "#{notif.actor.name} #{notif.action.humanize(capitalize: false)} your #{notif.notifiable.class.to_s.underscore.humanize.downcase}"  %>
          <span class='profile-notification-blue-dark'><%= notif.notifiable.name %></span>
          <br>
          <br>
          <%= button_to "Approve", action: "approve", notif: notif, class: "button profile-notif-button" %>
          <%= button_to "Deny", action: "deny", notif: notif, class: "button profile-notif-button" %>
        <% elsif notif.actor.approved %>
          <p> <%= notif.actor.name %> has been approved. </p>
        <% else %>
          <p> <%= notif.actor.name %> has been denied. </p>
        <% end %>
      <% else %>
        <%= notif.notifiable.anonymous ? "A volunteer" : notif.actor.name %> <%= "#{notif.action.humanize(capitalize: false)}. Please check the 'Reviews' tab in your profile." %>
      <% end %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/organization/_opp.html.erb
<% if @organization.opportunities.empty? %>
  <div class="opportunity">
    <div class="opp-approval">
        <span class="opp-approval-pink">No volunteer opportunities yet</span>
    </div>
  </div>
</br>
<% else %>
  <% @organization.opportunities.all.each do |f| %>
    <div class="level org-volunteer-level">
      <div class="level-item has-text-centered">
        <div>
          <div class="org-volunteer-name"><%= f.title%></div>
          <div class="org-volunteer-email"><%= f.location %></div>
        </div>
        </div>
      <div class="level-item has-text-centered">
        <div>
          <div class="light-blue-links"><%= link_to "view opportunity", opportunity_path(f) %></div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/organization/_stat.html.erb
<div class="org-stats">
    <div class="grey">
    <span class="pink"><%= @organization.volunteer_list().length() %></span> volunteers are interested in your events.
    </div>
    <div class="white">
    This week, your organization worked with <span class="pink"><%= @organization.weekly_volunteers() %></span> volunteers.
    </div>
    <div class="grey">
    This week, your organization contributed <span class="pink"><%= @organization.hours_this_week() %></span> hours to the community.
    </div>
    <br>
    <%= column_chart $weekly_stats, ytitle: "Hours", xtitle: "Week", title: "User Hours Recorded in Last Five Weeks" %>
    <%= column_chart $monthly_stats, ytitle: "Hours", xtitle: "Month", title: "User Hours Recorded in Last Six Months" %>
</div>

app/views/organization/feed_organization.js.erb
$('#link-wrap').append('<%= j render @opportunities %>');
<% if @opportunities.next_page %>
  $('.next_page').attr('href','<%= feed_organization_path(:page => @opportunities.next_page) %>');
<% else %>
  $('.more').remove();
<% end %>

app/views/organization/histories.js.erb
$("#tab-display").html("<%= escape_javascript(render partial: 'history') %>");
$(".custom-tab-stat").css("color", "rgb(181,181,181)");
$(".custom-tab-notif").css("color", "rgb(181,181,181");
$(".custom-tab-vol").css("color", "rgb(181,181,181");
$(".custom-tab-review").css("color", "rgb(181,181,181");
$(".custom-tab-opp").css("color", "rgb(181,181,181");
$(".custom-tab-history").css("color", "rgb(19,35,87)");

app/views/organization/new.html.erb
<!DOCTYPE html>
<html class="grey-background">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello Bulma!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    </head>

    <body>

        <div class="column-profile-left">
            <h1 class="new-opp-title">Register your organization</h1>
            
            <%= link_to '<button class="close-button">x</button>'.html_safe, :back %>

            <%= form_for :organization, url: new_organization_path, method: :get do |f| %>
                <% if @organization.errors.any? %>
                    <h2>Errors:</h2>
                    <ul>
                        <% @organization.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                <% end %>
                <p>
                    <%= f.label :name, "Name:" %><br>
                    <%= f.text_area :location, rows:2, cols:60 %>
                </p>

                <p>
                    <%= f.label :description, "Description:" %><br>
                    <%= f.text_area :description, rows:8, cols:120 %>
                </p>

                <p>
                    <%= f.label :location, "Location:" %><br>
                    <%= f.text_area :location, rows:4, cols:60 %>
                </p>

                <p>
                    <%= f.label :website, "Website:" %><br>
                    <%= f.text_field :website %>
                </p>

                <p>
                    <%= f.label :email, "Email:" %><br>
                    <%= f.text_field :email %>
                </p>

                <p>
                    <%= f.label :phone, "Phone number:" %><br>
                    <%= f.text_field :phone %>
                </p>

                <div class="create-button" >
                    <%= button_to 'New Organization', organization_path, method: :get, :class => 'button is-link' %>
                </div>

            <% end %>
        </div>
    </body>
</html>

app/views/organization/opps.js.erb
$("#tab-display").html("<%= escape_javascript(render partial: 'opp') %>");
$(".custom-tab-stat").css("color", "rgb(181,181,181)");
$(".custom-tab-notif").css("color", "rgb(181,181,181");
$(".custom-tab-vol").css("color", "rgb(181,181,181");
$(".custom-tab-review").css("color", "rgb(181,181,181");
$(".custom-tab-opp").css("color", "rgb(19,35,87)");
$(".custom-tab-history").css("color", "rgb(181,181,181");

app/views/organization/show.html.erb
<!DOCTYPE html>
<html class="grey-background">
  <head>
    <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
  </head>
  <body>

<!-- navigation bar -->
<%= render "layouts/navbar"%>

<!-- columns (first/left column is profile, second/right column is section with stats, notifs,
volunteers tabs) -->
<div class="columns">
  <div class="column is-one-third column-profile-left">

    <figure class="image has-image-centered">
      <% if !@organization.pictures.nil? && !@organization.pictures.find_by_name("Org#{@organization.id}pfp").nil? %>
        <%= image_tag @organization.pictures.find_by_name("Org#{@organization.id}pfp").image.url, style:"object-fit: cover; background-color: #F3F2F1;" %>
      <% else %>
        <%= image_tag "placeholder_profileorg.png"%>      
      <% end %>
    </figure>
    <div class="profile-title">
      <div> <%= @organization.name %>
        <% if @organization == current_user.organization %>
          <%= link_to edit_custom_path(id: current_user.id) do %>
            <span class="settings-icon"> <i class="fas fa-cog"></i> </span>
          <% end %>
        <% end %>

      </div>
    </div>

    <div class="profile-contact">
      <div class="posting-thumb">
        <i class="fas fa-thumbs-up"></i>
        <span class="thumb-text">
            <% if current_user.admin? || current_user.is_a?(OrgAdmin) %>
                <% if @organization.ratings.count == 0 %>
                    No people have liked this organization yet
                <% else %>
                    <%=@organization.ratings.count%> people like this organization!
                <% end %>
            <% else %>
                <% if @organization.ratings.count == 0 %>
                    No people have liked this organization yet
                <% elsif @organization.ratings.include?(Rating.find_by(user_id: current_user.id)) && @organization.ratings.count == 1 %>
                    You like this organization
                <% elsif @organization.ratings.include?(Rating.find_by(user_id: current_user.id)) && @organization.ratings.count > 1 %>
                    You and <%=@organization.ratings.count - 1%> other people like this organization!
                <% else %>
                    <%=@organization.ratings.count%> people like this organization!
                <% end %>
            <% end %>
        </span>
      </div>

      <div> <i class="far fa-envelope"></i>
          <%= if @organization.email.nil? then @organization.users.last.email else @organization.email end %>
      </div>

      <div> <i class="fas fa-phone-alt"></i>
        <%= if @organization.phone.nil? then @organization.users.last.phone else @organization.phone end %>
      </div>
    </div>
    <div class="profile-description">
        <% if @organization.description.nil? %> 
          No description listed
        <% else %> 
          <%= h @organization.description.html_safe %>
        <% end %>
    </div>

    <div class="profile-columns">
      <div class="columns is-centered is-gapless vol-profile-col">
        <div class="column is-half">
          <div class="profile-left-info">
            WEBSITE
          </div>
        </div>
        <div class="column">
          <div class="profile-right-info">
            <% if @organization.website.nil? %> No website listed
            <% else %>
                <div class="profile-right-info-hyperlink login-links">
                    <%= link_to @organization.website, @organization.website %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="columns is-centered is-gapless vol-profile-col">
        <div class="column is-half">
          <div class="profile-left-info">
            LOCATION
          </div>
        </div>
        <div class="column">
          <div class="profile-right-info">
            <% if @organization.location.nil? %>
              No address listed
            <% else %>
              <%= @organization.location %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>

      <% if user_signed_in? && current_user.is_a?(OrgAdmin) && current_user.organization == @organization %>
          <div id="navbarAuth">
              <div style="float: right;">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item button sign-in-button'  %>
              </div>
          </div>
          <br>
      <% elsif !current_user.admin? %>
          <% if !@organization.ratings.include?(Rating.find_by(user_id: current_user.id)) || !current_user.ratings.first.organizations.include?(@organization) %>
                <div style="justify-content: center">
                  <%= link_to '<span class="thumb-icon-profile"> <i class="far fa-thumbs-up"></i> </span>'.html_safe, like_action_path(id: @organization.id, like: 1), id: "like-org-profile" %>
                </div>
          <% else %>
                <span>
                    <%= link_to '<span class="thumb-icon-profile thumb-icon-profile-check"> <i class="far fa-thumbs-up"></i> </span>'.html_safe, like_action_path(id: @organization.id, like: 1), id: "like-org-profile" %>
                </span>
          <% end %>
      <% end %>
  </div>

<!-- stats page -->

  <div class="column is-three-fifths column-profile-right">
    <% if current_user.is_a?(OrgAdmin) && current_user.approved == true && current_user.organization == @organization %>
      <div class="tabs is-centered tabs-bar">
          <ul>
              <li><%= link_to 'stats', stats_path(@organization.id), :remote => true, class: "custom-tab-blue custom-tab-stat" %></li>
              <li><%= link_to 'notifications', notifications_path, :remote => true, class: "custom-tab-notif" %></li>
              <li><%= link_to 'volunteers', volunteers_path(@organization.id), :remote => true, class: "custom-tab-vol" %></li>
              <li><%= link_to 'reviews', reviews_path(@organization.id), :remote => true, class: "custom-tab-review" %></li>
          </ul>
      </div>

      <div id="tab-display">
        <%= render "stat" %>
      </div>

    <% else %>
      <div class="tabs is-centered tabs-bar">
        <ul>
        <% puts "-"*20 %>
            <li><%= link_to 'opportunities', opps_path(@organization.id), :remote => true, class: "custom-tab-blue custom-tab-opp" %></li>
            <% if !current_user.admin? && !current_user.is_a?(OrgAdmin) %>
                <li><%= link_to 'history', histories_path(@organization.id), :remote => true, class: "custom-tab-history" %></li>
            <% end %>
            <% if current_user.admin? %>
              <li><%= link_to 'stats', stats_path(@organization.id), :remote => true, class: "custom-tab-stat" %></li>
              <li><%= link_to 'volunteers', volunteers_path(@organization.id), :remote => true, class: "custom-tab-vol" %></li>
              <li><%= link_to 'reviews', reviews_path(@organization.id), :remote => true, class: "custom-tab-review" %></li>
            <% end %>
        </ul>
    </div>

    <div id="tab-display">
    <% if @organization.opportunities.empty? %>
      <div class="opportunity">
        <div class="opp-approval">
            <span class="opp-approval-pink">No volunteer opportunities yet</span>
        </div>
      </div>
    </br>
    <% else %>
      <% @organization.opportunities.all.each do |f| %>
      <div class="level org-volunteer-level">
        <div class="level-item has-text-centered">
          <div>
            <div class="org-volunteer-name"><%= f.title%></div>
            <div class="org-volunteer-email"><%= f.location %></div>
          </div>
          </div>
        <div class="level-item has-text-centered">
          <div>
            <div class="light-blue-links"><%= link_to "view opportunity", opportunity_path(f) %></div>
          </div>
        </div>
        </div>
      <% end %>
    </div>
    <% end %>
  <% end %>
  </div>
</div>
</div>
  </body>
</html>