config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "dashboard#index"
  get "/customize_complete" => "dashboard#customize_complete", as: "customize_interface"
  post "/customize_complete" => "dashboard#customize_complete", as: "customize_interface_form"
  get "/error404" => "dashboard#error404"
  get "/error500" => "dashboard#error500"
  get "/error403" => "dashboard#error403"
  get 'opportunities' => 'opportunities#index'
  get "/profile_volunteer" => "dashboard#profile_volunteer"
  #get "/profile_organization" => "organization#profile_organization"

  resources :organization
  get "/hours" => "dashboard#hours", as: "hours"
  get "/notifs" => "dashboard#notifs", as: "notifs"
  get "/history" => "dashboard#history", as: "history"
  get "/notifications" => "organization#notifications", as: "notifications"
  get "/stats/:id" => 'organization#stats', as: "stats"
  get "/volunteers/:id" => 'organization#volunteers', as: "volunteers"
  get "/reviews/:id" => 'organization#reviews', as: "reviews"
  get "/histories/:id" => 'organization#histories', as: "histories"
  get "/opps/:id" => 'organization#opps', as: "opps"
  get "/opportunities/:id/clone" => 'opportunities#clone', as: "clone_opportunity"
  post 'organization/approve'
  post 'organization/deny'

  resources :challenges
  get "/stat" => "admin#statistics"
  get "/requests" => "admin#requests"
  get "/organizations" => "admin#organizations"
  get "/goals" => "admin#goals"

  resources :opportunities
  get "/secret" => "organization#secret"
  get '/auth/duke-oauth2/callback', to: 'dashboard#create'
  get "/feed_volunteer" => "dashboard#feed_volunteer"
  post "/feed_volunteer" => "dashboard#feed_volunteer", as: "temp_form"
  post "/feed_organization" => "organization#feed_organization", as: "org_form"
  get "/feed_organization" => "organization#feed_organization"
  get "/admin" => "admin#admin_home"
  #get "/posting_volunteer" => "dashboard#posting_volunteer"
  get "/opportunities/:id/contact_volunteers" => "opportunities#contact_volunteers", as: "contact_volunteers"
  post "/opportunities/:id/contact" => "opportunities#contact", as: "contact_path"
  get "/opportunities/:id/view_volunteers" => "opportunities#view_volunteers", as: "view_volunteers"
  get "/organization/:id/like" => "organization#like", as: "like_action"
  get "/opportunities/:id/like" => "opportunities#like", as: "like_action_opportunity"

  get "/admin_home" => "admin#admin_home"
  get "/admin_settings" => "admin#admin_settings", as: "admin_settings"
  patch "/admin_home" => "admin#update_settings", as: "update_settings"
  post "/admin_home" => "admin#update_admin", as: "admin_form"
  
  get "/onboard" => "onboarding#onboard"
  get "/volunteer_partial" => "onboarding#volunteer_partial"
  get "/organization_partial" => "onboarding#organization_partial"
  get "/complete" => "onboarding#complete", as: "onboarding_complete"
  post "/complete" => "onboarding#complete", as: "onboarding_complete_form"
  post 'admin/approve'
  post 'admin/deny'

  get "/edit_user/:id" => "dashboard#edit_user", as: "edit_user"
  patch "/profile_volunteer" => "dashboard#update_user", as: "update_user"
  resources :dashboard, only: [:show]

  get "/edit_custom/:id" => "organization#edit_custom", as: "edit_custom"

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController

    # any line with 'if Interface.first.nil? redirect to root_url and return' ensures that the user is taken to the
    # homescreen and asked to create/customize an interface if it doesn't already exist (usually occurs with initial build)

    before_action :check_auth

    # Index page seen by organization admins
    def index
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @opportunities = Opportunity.all
        @organizations = Organization.all

        if !params[:freq].nil?
          @opportunities = @opportunities.filter_by_frequency(params[:freq])
        end

        if !params[:distance].nil?
          if !params[:location].nil?
              loc = params[:location]
          else
              loc = "Durham, NC 27708"
          end
          @opportunities = @opportunities.filter_by_distance(loc, params[:distance].to_i)
        end

        # Filter by tags and sort by upcoming and/or highest rated
        tags = params[:tags]
        @opportunities = @opportunities.filter_by_tags(tags) if tags.present?
        @opportunities = @opportunities.sorting(params[:upcoming], params[:highrated])

        #Puts featured posts at the top
        @opportunities = @opportunities.reorder(featured: :desc)

        @opportunities = @opportunities.paginate(:page => params[:page], :per_page => 5)

        respond_to do |format|
          format.html
          format.js
        end
    end

    # User liking an opportunity/organization
    def like
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @opportunity = Opportunity.find(params[:id])
        @organization = @opportunity.organization

        if !params[:like].nil? && !@organization.ratings.include?(Rating.find_by(user_id: current_user.id))
            if current_user.ratings.first.nil?
                rating = Rating.new(name:current_user.name)
                current_user.ratings << rating
            else
                rating = current_user.ratings.first
            end
            @organization.ratings << rating
        elsif !params[:like].nil?
            @organization.ratings.delete(Rating.find_by(user_id: current_user.id))
        end

        redirect_to @opportunity
    end

    def show
        if Interface.first.nil?
            redirect_to root_url and return
        end
        @interface = Interface.first

        @opportunity = Opportunity.find(params[:id])
        @organization = @opportunity.organization

        # Create notifications for organization
        if !params[:add].nil? && !current_user.opportunities.find_by_id(params[:id])
            current_user.opportunities << @opportunity
            @opportunity.organization.users.each do |user|
              Notification.create(recipient: user, actor: current_user,
                action: "has_signed_up_for", notifiable: @opportunity)
            end
            if @opportunity.require_approvals?
              UserMailer.signup_pending(current_user.email, @opportunity).deliver_now
            else
              UserMailer.signup_confirm(current_user.email, @opportunity).deliver_now
            end
            redirect_to @opportunity
        elsif !params[:add].nil?
            current_user.opportunities.delete(@opportunity)
            @opportunity.organization.users.each do |user|
              Notification.create(recipient: user, actor: current_user,
                action: "has_removed_their_sign_up_from", notifiable: @opportunity)
            end
            UserMailer.unsignup(current_user.email, @opportunity).deliver_now
            redirect_to @opportunity
        end

        # Updating featured attribute for opportunity
        if @opportunity.featured? && !params[:feature].nil?
            @opportunity.update_attribute(:featured, false)
            redirect_to @opportunity
        elsif !@opportunity.featured? && !params[:feature].nil?
            @opportunity.update_attribute(:featured, true)
            redirect_to @opportunity
        end
    end

    # Cloning an opportunity
    def clone
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @opportunity = Opportunity.new
        @opportunity_og = Opportunity.find(params[:id])
        @address = @opportunity_og.address
        @tags = Tag.all
    end

    def new
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @tags = Tag.all
        @opportunity = Opportunity.new
    end

    def create
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @organization = current_user.organization
        params["opportunity"]["date"] =  Opportunity.convert_date_string(params["opportunity"]["date"], params["time"])
        @opportunity = Opportunity.new(opportunities_params)
        address = {}
        if params["opportunity"]["address"]
          params["opportunity"]["address"].each {|k,v| address[k]=v}
          @opportunity.build_address(address)
        end
        @opportunity.active = 1
        tags = params[:tags]

        if !tags.nil?
            tags.each do |tag|
                @opportunity.tags << Tag.where(name: tag)
            end
        end

        if @organization.opportunities << @opportunity
            redirect_to @opportunity
        else
            @tags = Tag.all
            render 'new'
        end
    end

    def edit
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @opportunity = Opportunity.find(params[:id])
        @address = @opportunity.address
        @tags = Tag.all
    end

    def update
        if Interface.first.nil?
            redirect_to root_url and return
        end

        params["opportunity"]["date"] =  Opportunity.convert_date_string(params["opportunity"]["date"],
            params["time"])
        @opportunity = Opportunity.find(params[:id])
        address = {}
        params["opportunity"]["address"].each {|k,v| address[k]=v}
        @opportunity.build_address(address)

        @opportunity.tags.each do |n|
            @opportunity.tags.delete(n)
        end

        tags = params[:tags]

        if !tags.nil?
            tags.each do |tag|
                @opportunity.tags << Tag.where(name: tag)
            end
        end

        if(@opportunity.update(opportunities_params))
            redirect_to @opportunity
        else
            render 'edit'
        end

        # Notify users who are signed up that the opportunity has been editted
        @opportunity.users.all.each do |user|
          Notification.create(recipient: user, actor: current_user, action: "has_updated", notifiable: @opportunity)
        end
    end

    def destroy
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @opportunity = Opportunity.find(params[:id])
        @opportunity.destroy

        redirect_to which_feed
    end

    def contact_volunteers
        if Interface.first.nil?
            redirect_to root_url and return
        end

      @opportunity = Opportunity.find(params[:id])
    end

    # Viewing and approving volunteers
    def view_volunteers
        if Interface.first.nil?
            redirect_to root_url and return
        end

        @opportunity = Opportunity.find(params[:opp])
        if current_user.is_a?(OrgAdmin) && current_user.admin != true &&
            (current_user.approved != true || current_user.organization != @opportunity.organization)
            redirect_to "/error403"
        elsif !current_user.is_a?(OrgAdmin) && (!current_user.opportunities.include?(@opportunity) ||
            !@opportunity.approvals.include?(current_user.approvals.first))
            redirect_to "/error403"
        end

        @interface = Interface.first

        if !params[:user_id].nil?
            user = User.find(params[:user_id])
        end
        if !params[:approve].nil?
            if user.approvals.first.nil?
                app = Approval.new(name:user.name)
                app.user = user
                app.save
            end
            @opportunity.approvals << user.approvals.first
            Notification.create(recipient: user, actor: current_user,
                action: "has_approved_your_sign-up_for", notifiable: @opportunity)
            UserMailer.signup_approved(user.email, @opportunity).deliver_now
        elsif !params[:remove].nil?
            user.approvals.first.opportunities.delete(@opportunity)
            Notification.create(recipient: user, actor: current_user,
                action: "has_removed_approval_for", notifiable: @opportunity)
            UserMailer.signup_unapproved(user.email, @opportunity).deliver_now
        end
    end

    def contact
        if Interface.first.nil?
            redirect_to root_url and return
        end

      data = params[:body]
      subject=params[:subject]
      @opportunity = Opportunity.find(params[:id])
      to = params[:to].split(',')
      cc = params[:cc].split(',')
      bcc = params[:bcc].split(',')
      UserMailer.contact_all_volunteers(data,to,cc,bcc,subject).deliver_now
      redirect_to @opportunity
    end

    private def opportunities_params
        if Interface.first.nil?
            redirect_to root_url and return
        end

        params.require(:opportunity).permit(:date, :title, :description, :next_steps,
            :volunteers_needed, :hours, :poc_name, :poc_email, :poc_phone, :ongoing,
            :requirements, :preferences, :require_approvals, :remote, :link)
    end
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/opportunities/index.html.erb
<!-- problems to fix:
can we customize the checkboxes and slider?
filter button too
smh the size of the bookmark
fixed column sizes?
can we unclick the radio buttons
display of date/time and location
tags D:
-->

<!DOCTYPE html>
<html class="grey-background">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello Bulma!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    </head>

    <body>


  <!-- navigation bar -->
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
        <a href="/">
          <% if @interface.pictures.find_by_name("#{@interface.id}logo") %>
              <%= image_tag @interface.pictures.find_by_name("#{@interface.id}logo").image.url, :class=> "navbar-image" %>
          <% else %>
              <%= image_tag "navbar_logo.png", :class=>"navbar-image" %>
          <% end %>
        </a>
        </div>

            <div class="navbar-start" style="flex-grow: 1; justify-content: center; display: inline-flex;">
                <a class="navbar-item navbar-item-selected feedtab">
                    feed
                </a>

                <% if current_user.admin? %>
                    <%= link_to "dashboard", "/admin", class:"navbar-item navbar-item-grey" %>
                <% else %>
                    <%= link_to "dashboard", profile_volunteer_path, class:"navbar-item navbar-item-grey" %>
                <% end %>

                <!--
                <a class="navbar-item navbar-item-grey">
                    dashboard
                </a>
                -->

            </div>
        </div>
    </nav>

    <!-- left bar, contains filtering options -->
    <div class="columns">
        <div class="column is-one-fifth column-feed is-narrow">

            <%= form_tag(temp_form_path) do %>

                <!-- SORTING CHECKBOXES -->
                <div class="feed-left"> SORT BY: </div>
                <div>
                    <%= check_box_tag(:upcoming) %>
                    <span class="small-tab checkboxes"> <%= label_tag(:upcoming, "Upcoming") %> </span> <br>
                    <%= check_box_tag(:highrated) %>
                    <span class="small-tab checkboxes"> <%= label_tag(:highrated, "Most Liked") %> </span>
                </div>

                <!-- FILTERS -->
                <div class="feed-left"> FILTER BY: </div>
                <div class="checkboxes">
                    <label><input name="freq" value="one-time" type="radio" class="radio-box"> <span class="small-tab">One-Time</span></input></label>
                    <span>&#160;</span>
                    <label><input name="freq" value="ongoing" type="radio" class="radio-box"> <span class="small-tab">Ongoing</span></input></label>
                </div>

                <!-- SLIDER -->
                <div class="feed-left"> DISTANCE: </div>
                <script>
                    $(document).on('input change', '#distance', function() {
                        $('#distance_value').html( $(this).val() );
                    });
                </script>

                <!-- <input id="distanceSlider" class="slider has-output is-fullwidth" min="0" max="30" value="30" step="1" type="range"> -->
                <%= range_field_tag(:distance, 15, min:0.5, max:15, step:0.1, class:"slider has-output is-fullwidth", id:"distanceSlider")%>
                <p style="text-align:center">up to <output for="distanceSlider">15</output> miles away from:</p>
                <div class="checkboxes">
                    <input name="location" value="loc1" type="radio" class="radio-box"><span class="small-tab"><%= $loc1 %></span><br/>
                    <input name="location" value="loc2" type="radio" class="radio-box"><span class="small-tab"><%= $loc2 %></span><br/>
                    <input name="location" value="loc3" type="radio" class="radio-box"><span class="small-tab">3<%= $loc3 %></span><br/>
                </div>

                <!-- TAGS -->
                <div class="feed-left"> TAGS: </div>
                <div class="tags are-small tagbox">
                    <% Tag.all.each do |f| %>
                        <span class="tag is-rounded filter-custom-tag" name=<%= f.name %> ><%= f.name %></span>
                    <% end %>
                </div>

                <div>
                    <div id="tagInputContainer">
                        <%= submit_tag(" filter opportunities ", :class => "button filter-button is-centered is-fullwidth" ) %>
                        <% end %>
                    </div>
                </div>

                </br>
                </br>

                <div class="buttons is-centered saved">
                    <div class="button is-small feed-saved-button">
                        <i class="fas fa-user-check"></i>
                        <span class="small-tab">view sign ups</span>
                    </div>
                    <div class="button is-small feed-saved-button">
                        <i class="fas fa-history"></i>
                        <span class="small-tab">view volunteer history</span>
                    </div>
                </div>
        </div>

        <div class="column column-feed">
            <div id="link-wrap" >
                <%= render @opportunities %>
            </div>
            <% if @opportunities.next_page %>
                <div class="link more">
                    <%= link_to 'Load More', opportunities_path(:page => @opportunities.next_page), :class => "next_page button page-button", :remote => true if @opportunities.next_page %>
                </div>
            <% end %>
        </div>

    </div>
</body>

</html>

app/views/opportunities/show.html.erb
<!-- <h3><%= @opportunity.title %></h3>
<h4><%= @opportunity.location %></h4>
<p> Date: <%= @opportunity.display_date_time(@opportunity.date) %></p>
<p> Description: <%= @opportunity.description %></p>
<p><%= @opportunity.volunteers_needed %> Volunteers Needed </p>
<p> Tags:
    <% @opportunity.tags.each do |tag| %>
        <%= tag.name %>
    <% end %>
</p>
<p> Posted <%= time_ago_in_words(@opportunity.created_at)  %> ago </p>
<hr>
<%= link_to "Edit", edit_opportunity_path(@opportunity) %>
<%= link_to "Delete", opportunity_path(@opportunity), method: :delete, data: {confirm: "Are you sure you want to delete this opportunity?"} %>
<%= link_to "Opportunities", opportunities_path %> -->


<!DOCTYPE html>
<html class="grey-background">
<head>
    <script src="opps.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
</head>

<body>
    <!-- setting up for get directions link -->
    <% if !@opportunity.address.nil? %>
        <% url = "https://www.google.com/maps/search/?api=1&query=" %>
        <% street = @opportunity.address.street.split(" ") %>
        <% city = @opportunity.address.city.split(" ") %>
        <% destination = "" %>
        <% street.each do |f| %>
            <% destination = destination + f + "+" %>
        <% end %>
        <% city.each do |f| %>
            <% destination = destination + f + "+" %>
        <% end %>

        <% destination = destination + "%2C+#{@opportunity.address.state}" %>
        <% concatenated = url + destination %>
    <% end %>

  <!-- navigation bar -->
    <%= render "layouts/navbar"%>

    <div class="posting-container">
        <div>
            <%= link_to which_feed, class: "posting-arrow" do %>
                <i class="fas fa-arrow-left"></i>
            <% end %>
            <!--<span class="posting-bookmark disabled"><i class="far fa-bookmark"></i></span>-->
        </div>

        <div class="columns is-6">
            <div class="column is-three-quarters">
                <h1 class="posting-title"><%= @opportunity.title %> - </br>
                <%= @organization.name %>
                </h1>

                <div class="tags are-medium posting-tagbox">
                    <% @opportunity.tags.each do |f| %>
                        <span class="tag is-rounded posting-tag"><%= f.name %></span>
                    <% end %>
                </div>

                <div>
                    <span class="posting-text-bold"> Time commitment: </span>
                    <span class="posting-text tiny-tab">
                        <% if @opportunity.ongoing? %>
                            Ongoing
                        <% else %>
                            One-time -
                            <%= @opportunity.display_date_time(@opportunity.date) %>
                            for <%= @opportunity.hours %> hours
                        <% end %>
                    </span>
                    </br>
                </div>

                <div>
                <% if @opportunity.remote && !@opportunity.link.nil? %>
                    <span class="posting-text-bold"> Link: </span>
                    <span class="posting-text tiny-tab"><%= @opportunity.link %></span>
                    </br>
                <% elsif @opportunity.address.nil? %>
                    <span class="posting-text-bold"> Location: </span>
                    <span class="posting-text tiny-tab">No address listed</span>
                    </br>
                <% else %>
                    <span class="posting-text-bold"> Location: </span>
                    <span class="posting-text tiny-tab">
                        <%= @opportunity.address.printable_address  %>
                    </span>
                    <span class="tiny-tab">
                        <%= link_to "Get Directions", concatenated, class:"right-text-blue light-blue-links", style:"font-style:italic" %>
                    </span>
                    </br>
                <% end %>
                </div>

                </br>

                <div>
                    <span class="posting-text-bold"> Description: </span>
                    <div class="posting-text"> <%= @opportunity.description.html_safe %> </div>

                    </br>
                </div>

                <% if @opportunity.require_approvals? %>
                <div>
                    <% if current_user.is_a?(OrgAdmin) || current_user.admin? %>
                        <span class="posting-text-bold"> Information for approved volunteers: </span>

                        <% if !@opportunity.next_steps.nil? %>
                            <div class="posting-text"> <%= @opportunity.next_steps.html_safe %> </div>
                        <% else %>
                            <div class="posting-text"> There is no specified new information for approved volunteers. </div>
                        <% end %>

                    <% elsif current_user.opportunities.find_by_id(params[:id]) && @opportunity.approvals.include?(current_user.approvals.first)%>
                        <span class="posting-text-bold-pink"> Information for approved volunteers: </span>
                        <% if !@opportunity.next_steps.nil? %>
                            <div class="posting-text"> <%= @opportunity.next_steps.html_safe %> </div>
                        <% else %>
                            <div class="posting-text"> There is no specified new information for approved volunteers. </div>
                        <% end %>
                    <% end %>
                </div>
                <% end %>

                </br>
                </br>
                </br>

                <div>
                    <div class="posting-text">
                        Posted <%= time_ago_in_words(@opportunity.created_at)  %> ago
                    </div>
                </div>
            </div>
            <div class="column right-column">

                <% if !(current_user.is_a?(OrgAdmin)) && !current_user.admin? %>
                    <% if current_user.opportunities.find_by_id(params[:id]) %>
                        <div><%= link_to "I'm signed up!", opportunity_path(@opportunity, add: 1), id: "interested", class: "button is-centered right-button" %></div>
                        <span class="under-sign-up-text" id="click-again">Click again to remove your sign-up</span>
                        <br>
                    <% else %>
                        <div><%= link_to "Click to sign up", opportunity_path(@opportunity, add: 1), id: "interested", class: "button is-centered right-button" %></div>
                        <span class="under-sign-up-text" id="click-again">Click again to remove your sign-up</span>
                        <br>
                    <% end %>
                <% end %>

                <% if (current_user.admin?) %>
                    <% if @opportunity.featured? %>
                        <div class="right-column-featured-button" >
                            <%= link_to "Unfeature this post", opportunity_path(@opportunity, feature: 1), id: "featured", class: "button feature-button" %>
                        </div>
                    <% else %>
                        <div class="right-column-featured-button" >
                            <%= link_to "Feature this post", opportunity_path(@opportunity, feature: 1), id: "featured", class: "button feature-button" %>
                        </div>
                    <% end %>
                <% end %>

                <div class="right-text">
                    <p> Volunteers needed: <%= @opportunity.volunteers_needed %> </br>
                    Volunteers currently interested: <%= @opportunity.users.count %> </p>
                    </br>
                    <p> REQUIREMENTS: </br>
                    <% if @opportunity.requirements.nil? %> None
                    <% else %> <%= @opportunity.requirements.html_safe %> <% end %></p>
                    </br>
                    <p> PREFERENCES: </br>
                    <% if @opportunity.preferences.nil? %> None
                    <% else %> <%= @opportunity.preferences.html_safe %> <% end %> </p>
                    </br>

                    <div class="right-text-blue">
                        <p> POINT OF CONTACT: </p>
                            <% unless @opportunity.poc_name.blank? %>
                                <p>
                                    <%= @opportunity.poc_name %>
                                </p>
                            <% end %>
                            <% unless @opportunity.poc_email.blank? %>
                                <p class="light-blue-links">
                                    <%= mail_to @opportunity.poc_email %> </br>
                                </p>
                            <% end %>
                            <% unless @opportunity.poc_phone.blank? %>
                                <p>
                                    <%= @opportunity.poc_phone %> </br>
                                </p>
                            <% end %>

                        <br>

                        <% if current_user.is_a?(OrgAdmin) && current_user.approved == true && current_user.organization == @organization %>
                            <%= link_to "Edit this opportunity", edit_opportunity_path(@opportunity), :class=>"right-text-pink" %> <br>
                            <%= link_to "Delete this opportunity", opportunity_path(@opportunity), method: :delete, data: {confirm: "Are you sure you want to delete this opportunity?"}, :class=>"right-text-pink" %><br>
                            <%= link_to "Clone this opportunity", clone_opportunity_path(@opportunity.id), :class=>"right-text-pink" %><br>
                            <br>
                            <%= link_to "Contact volunteers", contact_volunteers_path(@opportunity.id), :class=>"right-text-pink" %> <br>
                            <%= link_to "View volunteer list", view_volunteers_path(opp: @opportunity.id), :class=>"right-text-pink" %>

                        <% elsif current_user.admin == true %>
                            <%= link_to "Visit this organization's profile ", organization_path(@organization), :class=>"right-text-pink" %><br>
                            <br>
                            <%= link_to "Edit this opportunity", edit_opportunity_path(@opportunity), :class=>"right-text-pink" %> <br>
                            <%= link_to "Delete this opportunity", opportunity_path(@opportunity), method: :delete, data: {confirm: "Are you sure you want to delete this opportunity?"}, :class=>"right-text-pink" %><br>
                            <%= link_to "View volunteer list", view_volunteers_path(opp: @opportunity.id), :class=>"right-text-pink" %> <br>

                        <% else %>
                            <%= link_to "Visit this organization's profile ", organization_path(@organization), :class=>"right-text-pink" %><br>
                            <% if !@organization.website.nil? %>
                                <%= link_to "Visit website", @organization.website, :class=>"right-text-pink" %><br>
                                <% if current_user.opportunities.find_by_id(params[:id]) && @opportunity.approvals.include?(current_user.approvals.first) %>
                                    <br>
                                    <%= link_to "View volunteer list", view_volunteers_path(opp: @opportunity.id), :class=>"right-text-pink" %>
                                <% end %>
                            <% end %>
                        <% end %> <br>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>